UI/WebStore/Components/BreadCrumbsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;

namespace WebStore.Components;

public class BreadCrumbsViewComponent : ViewComponent
{
    private readonly IProductData _ProductData;

    public BreadCrumbsViewComponent(IProductData ProductData) => _ProductData = ProductData;

    public IViewComponentResult Invoke()
    {
        var model = new BreadCrumbsViewModel();

        if (int.TryParse(Request.Query["SectionId"], out var section_id))
        {
            model.Section = _ProductData.GetSectionById(section_id);
            //if (model.Section?.ParentId is { } parent_section_id && model.Section.Parent is null)
            if (model.Section is { ParentId: { } parent_section_id, Parent: null })
                model.Section.Parent = _ProductData.GetSectionById(parent_section_id);
        }

        if(int.TryParse(Request.Query["BrandId"], out var brand_id))
            model.Brand = _ProductData.GetBrandById(brand_id);

        if (int.TryParse(Request.RouteValues["id"]?.ToString(), out var product_id))
            model.Product = _ProductData.GetProductById(product_id)?.Name;

        return View(model);
    }
}

UI/WebStore/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;
using WebStore.Services.Mapping;

namespace WebStore.Controllers;

public class CatalogController: Controller
{
    private const string __CatalogPageSize = "CatalogPageSize";

    private readonly IProductData _ProductData;
    private readonly IConfiguration _Configuration;

    public CatalogController(IProductData ProductData, IConfiguration Configuration)
    {
        _ProductData = ProductData;
        _Configuration = Configuration;
    }

    public IActionResult Index(int? SectionId, int? BrandId, int PageNumber = 1, int? PageSize = null)
    {
        var page_size = PageSize
            ?? (int.TryParse(_Configuration[__CatalogPageSize], out var value) ? value : null);

        var filter = new ProductFilter
        {
            BrandId = BrandId,
            SectionId = SectionId,
            PageNumber = PageNumber,
            PageSize = page_size,
        };

        var product_page = _ProductData.GetProducts(filter);

        return View(new CatalogViewModel
        {
            SectionId = SectionId,
            BrandId = BrandId,
            Products = product_page.Items
               .OrderBy(p => p.Order)
               .ToView()!,
            PageModel = new()
            {
                Page = PageNumber,
                PageSize = page_size ?? 0,
                TotalPages = product_page.PagesCount,
            }
        });
    }

    public IActionResult Details(int Id)
    {
        var product = _ProductData.GetProductById(Id);

        if (product is null)
            return NotFound();

        return View(product.ToView());
    }

    public IActionResult GetProductsView(int? SectionId, int? BrandId, int PageNumber = 1, int? PageSize = null)
    {
        var products = _ProductData.GetProducts(new()
        {
            BrandId = BrandId,
            SectionId = SectionId,
            PageNumber = PageNumber,
            PageSize = PageSize ?? _Configuration.GetValue(__CatalogPageSize, 6)
        });

        var products_views = products.Items.OrderBy(p => p.Order).ToView();

        return PartialView("Partial/_Products", products_views);
    }
}

UI/WebStore/Views/Catalog/Details.cshtml
@model WebStore.Domain.ViewModels.ProductViewModel
@{
    ViewBag.Title = "Информация о товаре";
}

<section>
    <div class="container">
        <vc:bread-crumbs/>

        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSideBar"/>
            </div>
            
            <div class="col-sm-9 padding-right">
                <div class="product-details"><!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">
                            <img src="~/images/shop/@Model.ImageUrl" alt="@Model.Name" />
                            <h3>ZOOM</h3>
                        </div>
                        <div id="similar-product" class="carousel slide" data-ride="carousel">
                            
                              <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <div class="item active">
                                      <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                      <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                      <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                    </div>
                                    <div class="item">
                                      <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                      <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                      <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                    </div>
                                    <div class="item">
                                      <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                      <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                      <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                    </div>
                                    
                                </div>

                              <!-- Controls -->
                              <a class="left item-control" href="#similar-product" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                              </a>
                              <a class="right item-control" href="#similar-product" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                              </a>
                        </div>

                    </div>
                    <div class="col-sm-7">
                        <div class="product-information"><!--/product-information-->
                            @*<img src="images/product-details/new.jpg" class="newarrival" alt="" />*@
                            <h2>@Model.Name</h2>
                            <p>Артикул: @Model.Id.ToString("00000000")</p>
                            <img src="~/images/product-details/rating.png" alt="" />
                            <span>
                                <span>@Model.Price.ToString("C")</span>
                                <label>Количество:</label>
                                <input type="text" value="3" />
                                <a class="btn btn-default add-to-cart" 
                                   data-id="@Model.Id"
                                   asp-controller="Cart" 
                                   asp-action="Add" 
                                   asp-route-Id="@Model.Id">
                                    <i class="fa fa-shopping-cart"></i>
                                    В корзину
                                </a>
                            </span>
                            <p><b>Доступность:</b> На складе</p>
                            <p><b>Состояние:</b> Новое</p>
                            <p><b>Brand:</b> @Model.Brand</p>
                            <p><b>Категория:</b> @Model.Section</p>
                            <a href="">
                                <img src="~/images/product-details/share.png" class="share img-responsive" alt=""/>
                            </a>
                        </div><!--/product-information-->
                    </div>
                </div><!--/product-details-->
                
                <partial name="Partial/_CategoryTab"/>

                <partial name="Partial/_RecomendedItems"/>
            </div>
        </div>
    </div>
</section>

UI/WebStore/Views/Catalog/Index.cshtml
@model WebStore.Domain.ViewModels.CatalogViewModel
@{
    ViewBag.Title = "Каталог товаров";
}

@*<section id="advertisement">
    <div class="container">
        <img src="~/images/shop/advertisement.jpg" alt="" />
    </div>
</section>*@

<section>
    <div class="container">
        <vc:bread-crumbs/>

        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSideBar"/>
            </div>

            <div class="col-sm-9 padding-right">
                <div id="catalog-container">
                    <partial name="Partial/_Products" model="Model.Products"/>
                </div>
                
                <paging page-model="Model.PageModel"
                        page-action="Index"
                        page-url-SectionId="@Model.SectionId"
                        page-url-BrandId="@Model.BrandId"
                        page-url-PageSize="@Context.Request.Query["PageSize"]">
                </paging>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <script src="~/lib/jquery-loading-overlay/loadingoverlay.min.js"></script>
    <script src="~/js/Catalog/CatalogLogic.js" asp-append-version="true"></script>
    <script>
        $(() => {
            Catalog.init({
                getViewLink: "@Url.Action("GetProductsView", "Catalog")"
            });
        })
    </script>
}