UI/WebStore/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Entities.Identity;
using WebStore.Interfaces.Services;

namespace WebStore.Areas.Admin.Controllers;

[Area("Admin"), Authorize(Roles = Role.Adinistrators)]
public class ProductsController : Controller
{
    private readonly IProductData _ProductData;
    private readonly ILogger<ProductsController> _Logger;

    public ProductsController(IProductData ProductData, ILogger<ProductsController> Logger)
    {
        _ProductData = ProductData;
        _Logger = Logger;
    }

    public IActionResult Index()
    {
        var products = _ProductData.GetProducts();
        return View(products.Items);
    }
}

UI/WebStore/Components/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;

namespace WebStore.Components;

public class BrandsViewComponent : ViewComponent
{
    private readonly IProductData _ProductData;

    public BrandsViewComponent(IProductData ProductData) => _ProductData = ProductData;

    public IViewComponentResult Invoke(string BrandId)
    {
        ViewBag.BrandId = (int.TryParse(BrandId, out var id) ? id : (int?)null)!;
        return View(GetBrands());
    }

    private IEnumerable<BrandViewModel> GetBrands() =>
        _ProductData.GetBrands()
           .OrderBy(b => b.Order)
           .Select(b => new BrandViewModel
            {
               Id = b.Id,
               Name = b.Name,
               ProductsCount = b.Products.Count,
            });
}

UI/WebStore/Controllers/AjaxTestController.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.ViewModels;

namespace WebStore.Controllers;

public class AjaxTestController : Controller
{
    private readonly ILogger<AjaxTestController> _Logger;

    public AjaxTestController(ILogger<AjaxTestController> Logger) => _Logger = Logger;

    public IActionResult Index() => View();

    public async Task<IActionResult> GetJSON(int? id, string? msg, int Delay = 2000)
    {
        _Logger.LogInformation("Поступил запрос на обработку данных к GetJSON - id:{0}, msg:{1}, Delay:{2}",
            id, msg, Delay);

        if (Delay > 0)
            await Task.Delay(Delay);

        _Logger.LogInformation("Обработка GetJSON завершена - id:{0}, msg:{1}, Delay:{2}",
            id, msg, Delay);

        return Json(new
        {
            Message = $"Response (id:{id ?? 0}): {msg ?? "--null--"}",
            ServerTime = DateTime.Now,
        });
    }

    public async Task<IActionResult> GetHTML(int? id, string? msg, int Delay = 2000)
    {
        _Logger.LogInformation("Поступил запрос на обработку данных к GetHTML - id:{0}, msg:{1}, Delay:{2}",
            id, msg, Delay);

        if (Delay > 0)
            await Task.Delay(Delay);

        _Logger.LogInformation("Обработка GetHTML завершена - id:{0}, msg:{1}, Delay:{2}",
            id, msg, Delay);

        return PartialView("Partial/_DataView", new AjaxTestDataViewModel
        {
            Id = id ?? 0,
            Message = msg ?? "--null--",
        });
    }

    public IActionResult Chat() => View();
}

UI/WebStore/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;
using WebStore.Services.Mapping;

namespace WebStore.Controllers;

public class CatalogController: Controller
{
    private const string __CatalogPageSize = "CatalogPageSize";

    private readonly IProductData _ProductData;
    private readonly IConfiguration _Configuration;

    public CatalogController(IProductData ProductData, IConfiguration Configuration)
    {
        _ProductData = ProductData;
        _Configuration = Configuration;
    }

    public IActionResult Index(int? SectionId, int? BrandId, int PageNumber = 1, int? PageSize = null)
    {
        var page_size = PageSize
            ?? (int.TryParse(_Configuration[__CatalogPageSize], out var value) ? value : null);

        var filter = new ProductFilter
        {
            BrandId = BrandId,
            SectionId = SectionId,
            PageNumber = PageNumber,
            PageSize = page_size,
        };

        var product_page = _ProductData.GetProducts(filter);

        return View(new CatalogViewModel
        {
            SectionId = SectionId,
            BrandId = BrandId,
            Products = product_page.Items
               .OrderBy(p => p.Order)
               .ToView()!,
            PageModel = new()
            {
                Page = PageNumber,
                PageSize = page_size ?? 0,
                TotalPages = product_page.PagesCount,
            }
        });
    }

    public IActionResult Details(int Id)
    {
        var product = _ProductData.GetProductById(Id);

        if (product is null)
            return NotFound();

        return View(product.ToView());
    }

    public IActionResult GetProductsView(int? SectionId, int? BrandId, int PageNumber = 1, int? PageSize = null)
    {
        var products = _ProductData.GetProducts(new()
        {
            BrandId = BrandId,
            SectionId = SectionId,
            PageNumber = PageNumber,
            PageSize = PageSize ?? _Configuration.GetValue(__CatalogPageSize, 6)
        });

        var products_views = products.Items.OrderBy(p => p.Order).ToView();

        return PartialView("Partial/_Products", products_views);
    }
}

UI/WebStore/Controllers/WebAPIController.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Interfaces.TestAPI;

namespace WebStore.Controllers
{
    public class WebAPIController : Controller
    {
        private readonly IValuesService _ValuesService;

        public WebAPIController(IValuesService ValuesService) => _ValuesService = ValuesService;

        public IActionResult Index()
        {
            var values = _ValuesService.GetValues();
            return View(values);
        }
    }
}

UI/WebStore/Views/Shared/Partial/_CategoryTab.cshtml
<div class="category-tab"><!--category-tab-->
    <div class="col-sm-12">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tshirt" data-toggle="tab">Рубашки</a></li>
            <li><a href="#blazers" data-toggle="tab">Blazers</a></li>
            <li><a href="#sunglass" data-toggle="tab">Sunglass</a></li>
            <li><a href="#kids" data-toggle="tab">Детские</a></li>
            <li><a href="#poloshirt" data-toggle="tab">Polo shirt</a></li>
        </ul>
    </div>
    <div class="tab-content">
        <div class="tab-pane fade active in" id="tshirt" >
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="blazers" >
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="sunglass" >
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="kids" >
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="poloshirt" >
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/category-tab-->

UI/WebStore/Views/Shared/Partial/_Footer.cshtml
<footer id="footer"><!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><span>e</span>-shopper</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe1.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                    
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe2.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                    
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe3.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                    
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe4.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="~/images/home/map.png" alt="" />
                        <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Service</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Онлайн помощь</a></li>
                            <li><a href="#">Связаться с нами</a></li>
                            <li><a href="#">Статус заказа</a></li>
                            <li><a href="#">Сменить положение</a></li>
                            <li><a href="#">ЧаВо</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Quock Магазин</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Рубашки</a></li>
                            <li><a href="#">Мужские</a></li>
                            <li><a href="#">Женские</a></li>
                            <li><a href="#">Подарочные сертификаты</a></li>
                            <li><a href="#">Обувь</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Policies</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Условия обслуживания</a></li>
                            <li><a href="#">Условия обработки приватной информации</a></li>
                            <li><a href="#">Условия возврата</a></li>
                            <li><a href="#">Платёжная система</a></li>
                            <li><a href="#">Чеки</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Информация о компании</a></li>
                            <li><a href="#">Карьера у нас</a></li>
                            <li><a href="#">Местоположение магазина</a></li>
                            <li><a href="#">Аффиллятная программа</a></li>
                            <li><a href="#">Авторские права</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                            <p>Получайте самые последние обновления с <br />нашего сайта и будьте в курсе событий сами...</p>
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
                <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
            </div>
        </div>
    </div>
</footer><!--/Footer-->

UI/WebStore/Views/Shared/Partial/_LeftSideBar.cshtml
@using WebStore.Components
<div class="left-sidebar">
    <vc:sections section-id="@Context.Request.Query["SectionID"]"/>

    <vc:brands brand-id="@Context.Request.Query["BrandId"]"/>

    <div class="price-range"><!--price-range-->
        <h2>Цены</h2>
        <div class="well text-center">
             <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
             <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
        </div>
    </div><!--/price-range-->

    <div class="shipping text-center"><!--shipping-->
        <img src="~/images/home/shipping.jpg" alt="" />
    </div><!--/shipping-->

</div>

UI/WebStore/Views/Shared/Partial/_MainMenu.cshtml
<div class="mainmenu pull-left">
    <ul class="nav navbar-nav collapse navbar-collapse">
        <li><a asp-controller="Home" asp-action="Index" class="active">Home</a></li>
        <li class="dropdown">
            <a ws-is-active-route ws-ignore-action asp-controller="Catalog" asp-action="Index">Магазин<i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
                <li><a ws-is-active-route asp-controller="Catalog" asp-action="Index">Каталог</a></li>
            </ul>
        </li> 
        <li class="dropdown"><a href="#">Блог<i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
                <li><a href="blog.html">Список блогов</a></li>
                <li><a href="blog-single.html">Блог магазина</a></li>
            </ul>
        </li> 
        <li><a ws-is-active-route asp-controller="Employees" asp-action="Index">Сотрудники</a></li>
        <li><a asp-controller="WebAPI" asp-action="Index" class="@IsActive("WebAPI")">WebAPI</a></li>
        <li><a ws-is-active-route asp-controller="AjaxTest" asp-action="Index">AJAX</a></li>
        <li><a ws-is-active-route asp-controller="AjaxTest" asp-action="Chat">Chat</a></li>
    </ul>
</div>

@functions
{
    string? IsActive(string Controller, string Action = "Index") =>
        Equals(Controller, ViewContext.RouteData.Values["controller"]) &&
        Equals(Action, ViewContext.RouteData.Values["action"])
            ? "active"
            : null;
}

UI/WebStore/Views/Shared/Partial/_Products.cshtml
@model IEnumerable<WebStore.Domain.ViewModels.ProductViewModel>

<div class="features_items"><!--features_items-->
    <h2 class="title text-center">Товары</h2>
    
    @foreach (var product in Model)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/images/shop/@product.ImageUrl" alt="@product.Name" />
                        <h2>@product.Price.ToString("C2")</h2>
                        <p>
                            <a asp-controller="Catalog" 
                               asp-action="Details" 
                               asp-route-Id="@product.Id"
                               asp-route-BrandId="@Context.Request.Query["BrandId"]"
                               asp-route-SectionId="@Context.Request.Query["SectionId"]">
                                @product.Name
                            </a>
                        </p>
                        <a class="btn btn-default add-to-cart" 
                           data-id="@product.Id"
                           asp-controller="Cart" 
                           asp-action="Add" 
                           asp-route-Id="@product.Id">
                            <i class="fa fa-shopping-cart"></i>В корзину
                        </a>
                    </div>
                    <div class="product-overlay">
                        <div class="overlay-content">
                            <h2>@product.Price.ToString("C2")</h2>
                            <p>
                                <a asp-controller="Catalog" 
                                   asp-action="Details" 
                                   asp-route-Id="@product.Id"
                                   asp-route-BrandId="@Context.Request.Query["BrandId"]"
                                   asp-route-SectionId="@Context.Request.Query["SectionId"]">
                                    @product.Name
                                </a>
                            </p>
                            <a class="btn btn-default add-to-cart" 
                               data-id="@product.Id"
                               asp-controller="Cart" 
                               asp-action="Add" 
                               asp-route-Id="@product.Id">
                                <i class="fa fa-shopping-cart"></i>В корзину
                            </a>
                        </div>
                    </div>
                </div>
                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Добавить в желания</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Добавить к сравнению</a></li>
                    </ul>
                </div>
            </div>
        </div>
    }

</div><!--features_items-->